// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026web3.Data;

#nullable disable

namespace _2026web3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MateriaPersona", b =>
                {
                    b.Property<int>("MateriasId")
                        .HasColumnType("int");

                    b.Property<int>("PersonasId")
                        .HasColumnType("int");

                    b.HasKey("MateriasId", "PersonasId");

                    b.HasIndex("PersonasId");

                    b.ToTable("Inscripcion", (string)null);

                    b.HasData(
                        new
                        {
                            MateriasId = 1,
                            PersonasId = 1
                        },
                        new
                        {
                            MateriasId = 2,
                            PersonasId = 1
                        },
                        new
                        {
                            MateriasId = 3,
                            PersonasId = 1
                        },
                        new
                        {
                            MateriasId = 2,
                            PersonasId = 2
                        },
                        new
                        {
                            MateriasId = 5,
                            PersonasId = 2
                        },
                        new
                        {
                            MateriasId = 1,
                            PersonasId = 3
                        },
                        new
                        {
                            MateriasId = 4,
                            PersonasId = 3
                        },
                        new
                        {
                            MateriasId = 3,
                            PersonasId = 4
                        },
                        new
                        {
                            MateriasId = 2,
                            PersonasId = 5
                        },
                        new
                        {
                            MateriasId = 3,
                            PersonasId = 5
                        },
                        new
                        {
                            MateriasId = 4,
                            PersonasId = 5
                        });
                });

            modelBuilder.Entity("_2026web3.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creditos = 5,
                            Name = "Programación I"
                        },
                        new
                        {
                            Id = 2,
                            Creditos = 4,
                            Name = "Bases de Datos"
                        },
                        new
                        {
                            Id = 3,
                            Creditos = 5,
                            Name = "Desarrollo Web"
                        },
                        new
                        {
                            Id = 4,
                            Creditos = 3,
                            Name = "Matemática Discreta"
                        },
                        new
                        {
                            Id = 5,
                            Creditos = 4,
                            Name = "Redes de Computadoras"
                        });
                });

            modelBuilder.Entity("_2026web3.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 2,
                            Name = "México"
                        },
                        new
                        {
                            Id = 3,
                            Name = "España"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Argentina"
                        });
                });

            modelBuilder.Entity("_2026web3.Models.Pasaporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("personaId")
                        .IsUnique();

                    b.ToTable("Pasaporte");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Numero = "GT1234567",
                            personaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Numero = "MX7654321",
                            personaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Numero = "ES1122334",
                            personaId = 3
                        });
                });

            modelBuilder.Entity("_2026web3.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("dob")
                        .HasColumnType("date");

                    b.Property<int>("paisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("paisId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ana López",
                            dob = new DateOnly(2000, 3, 15),
                            paisId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carlos Ramírez",
                            dob = new DateOnly(1998, 7, 2),
                            paisId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "María Fernández",
                            dob = new DateOnly(2001, 11, 20),
                            paisId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jorge Castillo",
                            dob = new DateOnly(1999, 1, 8),
                            paisId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lucía Morales",
                            dob = new DateOnly(2002, 6, 30),
                            paisId = 5
                        });
                });

            modelBuilder.Entity("MateriaPersona", b =>
                {
                    b.HasOne("_2026web3.Models.Materia", null)
                        .WithMany()
                        .HasForeignKey("MateriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026web3.Models.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2026web3.Models.Pasaporte", b =>
                {
                    b.HasOne("_2026web3.Models.Persona", "Persona")
                        .WithOne("Pasaporte")
                        .HasForeignKey("_2026web3.Models.Pasaporte", "personaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("_2026web3.Models.Persona", b =>
                {
                    b.HasOne("_2026web3.Models.Pais", "Pais")
                        .WithMany("Personas")
                        .HasForeignKey("paisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("_2026web3.Models.Pais", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("_2026web3.Models.Persona", b =>
                {
                    b.Navigation("Pasaporte");
                });
#pragma warning restore 612, 618
        }
    }
}
